services:
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: microservice-user
    volumes:
      - postgres_db_user:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "25432:5432"
    networks:
      user-network:

  redis:
    container_name: redis-user
    image: redis
    ports:
      - "6379:6379"
    networks:
      user-network:

  hire-me-microservice-user:
    image: hire-me-microservice-user
    networks:
      hire-me-network:
      user-network:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hire-me-microservice-user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/microservice-user
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_db_user:

networks:
  user-network:
    driver: bridge
  hire-me-network:
    external: true
    name: hire-me-network
